### PR TITLE
Fix readme

### PR DESCRIPTION
**Pull request by scorphus**

### CODE REVIEW

**Comment by animatedmax** [comment]
Hi @scorphus 

Thanks for submitting this pull request!

All pull request authors must have a Contributor License Agreement (CLA) on-file with us. Please sign the appropriate CLA ([individual](http://cloudfoundry.org/pdfs/CFF_Individual_CLA.pdf) or [corporate](http://cloudfoundry.org/pdfs/CFF_Corporate_CLA.pdf)).

When sending signed CLA please provide your github username in case of individual CLA or the list of github usernames that can make pull requests on behalf of your organization.

If you are confident that you're covered under a Corporate CLA, please make sure you've publicized your membership in the appropriate Github Org, per [these instructions](https://help.github.com/articles/publicizing-or-concealing-organization-membership/).

Thanks again!

**Comment by scorphus** [comment]
Hello, @animatedmax!

I've signed and sent the CLA to the proper recipient email address.

If there's anything else I should do, please let me know.

Thanks!

**Comment by animatedmax** [comment]
Hi @scorphus GitHub won't let me merge this PR in automatically, so I pulled your changes into the README manually. Thanks you!

**Comment by scorphus** [comment]
Let me fix these conflicts...

**Comment by scorphus** [comment]
Oh... :frowning: too bad the commit isn't attributed to me at all :disappointed: I would happily fix any conflicts. That's a shame.

I'm wondering why the CLA was needed in the first place! :confused:

**Comment by scorphus** [comment]
Oh... perhaps now I understand the need for a CLA!

:-1:

**Comment by animatedmax** [comment]
Hi @scorphus I'm happy to back the changes out so that we can get you on the commit -- let me know and I'll retract the last commit. Thanks!

**Comment by scorphus** [comment]
We're good to go! No more conflicts :wink:

**Comment by animatedmax** [comment]
Thank you @scorphus !

**Pull request merged**
